/**
 * matters.ts — Client matter CRUD with Kimball SCD Type 2 semantics.
 *
 * All writes preserve history:
 *   - New rows are inserted with is_current=true, effective_date=now().
 *   - Deletes are soft-deletes (deleted_at=now()), row is never removed.
 *   - associateQuery increments counters in-place on the current row.
 *
 * Auth: CLAUDE_CODE_OAUTH_TOKEN (never ANTHROPIC_API_KEY).
 */

import {
  Ok,
  Err,
  MatterId,
  ClientMatter,
  type Result,
  type MatterUsageStats,
} from "./types.js";
import { getSql } from "./db.js";

// ── Public API ───────────────────────────────────────────────

/**
 * Inserts one or more new client matters into julia_client_matters.
 *
 * Each row is created with is_current=true and effective_date=now().
 * Returns an array of branded MatterIds in insertion order.
 *
 * @param matters - Array of matter name + optional description.
 * @returns Ok(MatterId[]) on success, Err on database failure.
 */
export async function addMatters(
  matters: Array<{ name: string; description?: string }>,
): Promise<Result<MatterId[]>> {
  if (matters.length === 0) {
    return Ok([]);
  }

  try {
    const sqlResult = getSql();
    if (!sqlResult.ok) return sqlResult;
    const sql = sqlResult.value;

    // Build a multi-row VALUES list with positional parameters.
    // Each matter produces 2 params (name, description); id and timestamps
    // are generated by the database.
    const ids: MatterId[] = [];
    for (const matter of matters) {
      const rows = await sql`
        INSERT INTO julia_client_matters
          (name, description, status, query_count, token_count,
           metadata, effective_date, is_current, created_at, updated_at)
        VALUES
          (${matter.name},
           ${matter.description ?? ""},
           'active',
           0,
           0,
           '{}',
           now(),
           true,
           now(),
           now())
        RETURNING id
      `;
      const row = rows[0];
      if (!row) {
        return Err({ type: "database_error", message: "INSERT returned no row" });
      }
      ids.push(MatterId(row["id"] as string));
    }

    return Ok(ids);
  } catch (err) {
    return Err({
      type: "database_error",
      message: err instanceof Error ? err.message : String(err),
    });
  }
}

/**
 * Fetches all current, non-deleted client matters.
 *
 * Returns a Map keyed by branded MatterId so callers can do O(1)
 * lookups without re-scanning the array. Each value merges
 * ClientMatter fields with its MatterUsageStats.
 *
 * @returns Ok(Map<MatterId, ClientMatter & { usage: MatterUsageStats }>)
 *          on success, Err on database failure.
 */
export async function getMatters(): Promise<
  Result<Map<MatterId, ClientMatter & { usage: MatterUsageStats }>>
> {
  try {
    const sqlResult = getSql();
    if (!sqlResult.ok) return sqlResult;
    const sql = sqlResult.value;
    const rows = await sql`
      SELECT
        id,
        name,
        description,
        status,
        query_count,
        token_count,
        metadata,
        effective_date,
        expiration_date,
        is_current,
        created_at,
        updated_at,
        deleted_at
      FROM julia_client_matters
      WHERE is_current = true
        AND deleted_at IS NULL
      ORDER BY created_at ASC
    `;

    const map = new Map<MatterId, ClientMatter & { usage: MatterUsageStats }>();

    for (const row of rows) {
      const matter = ClientMatter.fromRow(row as Record<string, unknown>);
      const usage: MatterUsageStats = {
        query_count: matter.query_count,
        token_count: matter.token_count,
        // julia_client_matters has no last_query_at column; derive from
        // updated_at when query_count > 0, otherwise null.
        // TODO: add a last_query_at column to the schema for precision.
        last_query_at: matter.query_count > 0 ? matter.updated_at : null,
      };
      map.set(matter.id, { ...matter, usage });
    }

    return Ok(map);
  } catch (err) {
    return Err({
      type: "database_error",
      message: err instanceof Error ? err.message : String(err),
    });
  }
}

/**
 * Soft-deletes client matters by setting deleted_at=now().
 *
 * Only affects rows where is_current=true and deleted_at IS NULL.
 * Rows are never physically removed (SCD Type 2 history is preserved).
 *
 * @param ids - Branded MatterIds to delete.
 * @returns Ok(void) on success, Err on database failure.
 */
export async function deleteMatters(ids: MatterId[]): Promise<Result<void>> {
  if (ids.length === 0) {
    return Ok(undefined);
  }

  try {
    const sqlResult = getSql();
    if (!sqlResult.ok) return sqlResult;
    const sql = sqlResult.value;
    // Cast to text[] so Neon can bind the array parameter.
    await sql`
      UPDATE julia_client_matters
      SET    deleted_at = now(),
             updated_at = now()
      WHERE  id = ANY(${ids as string[]}::text[])
        AND  is_current = true
        AND  deleted_at IS NULL
    `;
    return Ok(undefined);
  } catch (err) {
    return Err({
      type: "database_error",
      message: err instanceof Error ? err.message : String(err),
    });
  }
}

/**
 * Increments query_count and token_count for a matter.
 *
 * Called after every completion that is associated with a matter so
 * usage statistics stay current without a separate analytics query.
 *
 * @param matterId - The matter to credit.
 * @param tokens   - Number of tokens used in the query.
 * @returns Ok(void) on success, Err on database failure.
 */
export async function associateQuery(
  matterId: MatterId,
  tokens: number,
): Promise<Result<void>> {
  try {
    const sqlResult = getSql();
    if (!sqlResult.ok) return sqlResult;
    const sql = sqlResult.value;
    await sql`
      UPDATE julia_client_matters
      SET    query_count = query_count + 1,
             token_count = token_count + ${tokens},
             updated_at  = now()
      WHERE  id         = ${matterId as string}
        AND  is_current = true
        AND  deleted_at IS NULL
    `;
    return Ok(undefined);
  } catch (err) {
    return Err({
      type: "database_error",
      message: err instanceof Error ? err.message : String(err),
    });
  }
}
